-- Schema seed data: collections, pieces, assignments
-- Generated by scripts/convert-seed.mjs

TRUNCATE practice_tasks, section_status_snapshots, piece_section_timestamps, piece_videos, piece_sections, assignments, pieces, collections CASCADE;

-- Collections
INSERT INTO collections (id, name, composer, notes, created_at, updated_at) VALUES
  ('230825a8-c840-49bf-a4b9-f80b76b7c54f', 'Ballades', 'Chopin', '', '2026-03-19 15:35:58.525042+00', '2026-03-19 15:35:58.525042+00');

-- Pieces
INSERT INTO pieces (id, collection_id, name, composer, status, kind, notes, target_tempo, created_at, updated_at) VALUES
  ('c6b8d48f-e6de-41ce-bd32-5ec49b40de23', NULL, 'Scherzo No. 1', 'Chopin', 'active', 'piece', '', 160, '2026-03-19 04:34:06.888135+00', '2026-03-19 15:33:23.12205+00'),
  ('671174b8-96df-46b9-bc39-2ceb999a22da', NULL, 'Trio in G major', 'Debussy', 'active', 'piece', '', 65, '2026-03-19 14:30:53.221713+00', '2026-03-19 14:30:53.221713+00'),
  ('e07a9e85-307a-4af9-8966-d1e824ec9ddb', NULL, 'Ballade 4', 'Chopin', 'active', 'piece', '', 176, '2026-03-19 15:35:20.96941+00', '2026-03-19 15:35:20.96941+00'),
  ('b1a2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d', NULL, 'Quintet in G minor', 'Bruch', 'active', 'piece', '', NULL, '2025-11-13 14:00:00+00', '2025-11-13 14:00:00+00'),
  ('a2b3c4d5-e6f7-4a8b-9c0d-1e2f3a4b5c6d', NULL, 'Prelude 10', 'Bach', 'active', 'piece', '', NULL, '2025-11-13 14:00:00+00', '2025-11-13 14:00:00+00'),
  ('c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f', NULL, 'Sonata 18 EbM', 'Beethoven', 'archived', 'piece', '', NULL, '2025-11-13 14:00:00+00', '2025-11-13 14:00:00+00'),
  ('00000000-0000-0000-0000-000000000001', NULL, 'Technique', '', 'active', 'technique', '', NULL, '2025-01-01 00:00:00+00', '2025-01-01 00:00:00+00'),
  ('00000000-0000-0000-0000-000000000002', NULL, 'Sight Reading', '', 'active', 'sight_reading', '', NULL, '2025-01-01 00:00:00+00', '2025-01-01 00:00:00+00');

-- Assignments
INSERT INTO assignments (id, piece_id, text, completed, completed_at, created_at, updated_at) VALUES
  ('d1000001-0003-4001-8001-000000000003', 'b1a2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d', 'Work on Bruch Quintet', true, '2025-10-26 18:00:00+00', '2025-10-26 18:00:00+00', '2025-10-26 18:00:00+00'),
  ('d1000001-0007-4001-8001-000000000007', 'e07a9e85-307a-4af9-8966-d1e824ec9ddb', 'Ballade - bass as separate idea, practice LH thumb', true, '2025-11-13 18:00:00+00', '2025-11-13 18:00:00+00', '2025-11-13 18:00:00+00'),
  ('d1000001-0009-4001-8001-000000000009', 'c6b8d48f-e6de-41ce-bd32-5ec49b40de23', 'Scherzo - practice just the bass line', true, '2025-11-20 18:00:00+00', '2025-11-20 18:00:00+00', '2025-11-20 18:00:00+00'),
  ('d1000001-000a-4001-8001-00000000000a', 'c6b8d48f-e6de-41ce-bd32-5ec49b40de23', 'Scherzo coda chromatic scales', true, '2025-12-06 18:00:00+00', '2025-12-06 18:00:00+00', '2025-12-06 18:00:00+00'),
  ('d1000001-000b-4001-8001-00000000000b', 'e07a9e85-307a-4af9-8966-d1e824ec9ddb', 'Ballade Theme 2 @40', true, '2026-02-24 18:00:00+00', '2026-02-24 18:00:00+00', '2026-02-24 18:00:00+00'),
  ('d1000001-000c-4001-8001-00000000000c', 'e07a9e85-307a-4af9-8966-d1e824ec9ddb', 'Ballade Coda @40', true, '2026-02-24 18:00:00+00', '2026-02-24 18:00:00+00', '2026-02-24 18:00:00+00'),
  ('d1000001-000d-4001-8001-00000000000d', 'e07a9e85-307a-4af9-8966-d1e824ec9ddb', 'Pre-coda arpeggios @72', true, '2026-02-24 18:00:00+00', '2026-02-24 18:00:00+00', '2026-02-24 18:00:00+00'),
  ('d1000001-000e-4001-8001-00000000000e', 'c6b8d48f-e6de-41ce-bd32-5ec49b40de23', 'Scherzo Coda @40', true, '2026-02-24 18:00:00+00', '2026-02-24 18:00:00+00', '2026-02-24 18:00:00+00'),
  ('d1000001-000f-4001-8001-00000000000f', 'e07a9e85-307a-4af9-8966-d1e824ec9ddb', 'Ballade Theme 1 variation II', false, NULL, '2026-03-05 18:00:00+00', '2026-03-05 18:00:00+00'),
  ('d1000001-0010-4001-8001-000000000010', 'c6b8d48f-e6de-41ce-bd32-5ec49b40de23', 'Scherzo Coda @60', false, NULL, '2026-03-05 18:00:00+00', '2026-03-05 18:00:00+00'),
  ('d1000001-0012-4001-8001-000000000012', 'c6b8d48f-e6de-41ce-bd32-5ec49b40de23', 'Bring Scherzo score - play and explain marks', true, '2026-03-12 18:00:00+00', '2026-03-12 18:00:00+00', '2026-03-12 18:00:00+00'),
  ('dff48827-5ad6-4c6e-8372-c8a2a329c4fd', 'c6b8d48f-e6de-41ce-bd32-5ec49b40de23', 'Yes this is a nice thing', false, NULL, '2026-03-19 13:00:00+00', '2026-03-19 13:00:00+00'),
  ('9f4ac81d-81ae-4276-90b6-584e21abc731', 'c6b8d48f-e6de-41ce-bd32-5ec49b40de23', 'Do this', false, NULL, '2026-03-19 13:00:01+00', '2026-03-19 13:00:01+00'),
  ('f8438861-34f0-47b0-9100-8937c6e03b24', '671174b8-96df-46b9-bc39-2ceb999a22da', 'Play the piece at', false, NULL, '2026-03-19 13:00:00+00', '2026-03-19 13:00:00+00'),
  ('02d7e47d-21a1-4ada-8349-986a2d06dbe7', 'e07a9e85-307a-4af9-8966-d1e824ec9ddb', 'Learn the m72', false, NULL, '2026-03-19 13:00:00+00', '2026-03-19 13:00:00+00');
