import type { ReactNode } from "react";
import { cn } from "@/lib/utils";

// Each variant points at a different torn-edge filter: `card` tears with a
// larger amplitude for full-size feed/detail images, `thumb` uses a tighter,
// shallower tear so the effect still reads at ~64px.
const VARIANTS = {
  card: "[filter:url(#ai-torn-edge)]",
  thumb: "[filter:url(#ai-torn-edge-sm)]",
} as const;

/**
 * Marks a photo as AI-generated by giving it a hand-torn, ripped-page edge
 * instead of the clean rounded rectangle uploaded photos get. The irregular
 * deckle reads as "different" at a glance — no badge or icon needed — and the
 * soft drop shadow lifts it off the page like a clipping in a scrapbook.
 *
 * The tear comes from an SVG turbulence/displacement filter (defined inline
 * below); it cuts into the image itself, so the media should fill the frame.
 */
export function AiPhotoFrame({
  children,
  className,
  variant = "card",
  fill = true,
}: {
  children: ReactNode;
  className?: string;
  variant?: keyof typeof VARIANTS;
  /** Force the media area to fill a fixed-size frame; set false to shrink-wrap
   * around free-sized media (e.g. the lightbox). */
  fill?: boolean;
}) {
  return (
    <>
      <div
        className={cn(
          "relative bg-muted",
          VARIANTS[variant],
          fill && "h-full w-full",
          className
        )}
      >
        {children}
      </div>
      <TornEdgeDefs />
    </>
  );
}

// Inline filter definitions. Rendered once per frame; the ids are constant, so
// multiple copies all resolve to the same (identical) filter — harmless. Kept
// in the component so any surface using AiPhotoFrame works without wiring defs
// into a layout. fractalNoise drives the raggedness; feDisplacementMap pushes
// the image edges along it; feDropShadow adds a soft warm lift.
function TornEdgeDefs() {
  return (
    <svg
      aria-hidden
      focusable={false}
      className="pointer-events-none absolute h-0 w-0"
    >
      <defs>
        <filter
          id="ai-torn-edge"
          x="-20%"
          y="-20%"
          width="140%"
          height="140%"
          colorInterpolationFilters="sRGB"
        >
          <feTurbulence
            type="fractalNoise"
            baseFrequency="0.015"
            numOctaves={2}
            seed={8}
            result="noise"
          />
          <feDisplacementMap
            in="SourceGraphic"
            in2="noise"
            scale={8}
            xChannelSelector="R"
            yChannelSelector="G"
            result="torn"
          />
          <feDropShadow
            dx={0}
            dy={2}
            stdDeviation={3}
            floodColor="#3a2a18"
            floodOpacity={0.25}
          />
        </filter>
        <filter
          id="ai-torn-edge-sm"
          x="-20%"
          y="-20%"
          width="140%"
          height="140%"
          colorInterpolationFilters="sRGB"
        >
          <feTurbulence
            type="fractalNoise"
            baseFrequency="0.06"
            numOctaves={2}
            seed={8}
            result="noise"
          />
          <feDisplacementMap
            in="SourceGraphic"
            in2="noise"
            scale={4}
            xChannelSelector="R"
            yChannelSelector="G"
            result="torn"
          />
          <feDropShadow
            dx={0}
            dy={1}
            stdDeviation={2}
            floodColor="#3a2a18"
            floodOpacity={0.2}
          />
        </filter>
      </defs>
    </svg>
  );
}
